Definition ${mp.methodName} "${mp.methodLabel}" "${mp.parentLabel}"  "${mp.optionLabel}" {


<#include "section/data.ftlh" />
<#include "section/init.ftlh" />
<#include "section/typeMask.ftlh" />
<#include "section/underlyingList.ftlh" />
<#include "section/underlyingMask.ftlh" />
<#include "section/optionList.ftlh" />
<#include "section/optionListLabel.ftlh" />
<#include "section/optionMask.ftlh" />

}